# Generated by Django 2.1.4 on 2018-12-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arfi', '0001_add_revenue_cycle_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diperbaharui')),
                ('quantity', models.BigIntegerField(default=0, verbose_name='Quantity')),
                ('price', models.BigIntegerField(default=0, verbose_name='Harga')),
            ],
            options={
                'verbose_name': 'Inventory List',
                'verbose_name_plural': 'Inventory Lists',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Tanggal')),
                ('bill', models.BigIntegerField(verbose_name='Tagihan')),
                ('total', models.BigIntegerField(verbose_name='Total')),
                ('confirmation', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='PO. Number')),
                ('date', models.DateTimeField(verbose_name='Tanggal')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='ReceivingReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='PO. Number')),
                ('date', models.DateTimeField(verbose_name='Tanggal')),
            ],
            options={
                'verbose_name': 'Receiving Report',
                'verbose_name_plural': 'Receiving Reports',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Mandor')),
                ('address', models.CharField(max_length=200, verbose_name='Alamat')),
                ('phone', models.CharField(max_length=20, verbose_name='No. HP')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=1, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.Item', verbose_name='Item')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.PurchaseOrder', verbose_name='Purchase Order')),
                ('receiving_report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.ReceivingReport', verbose_name='Receiving Report')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AlterModelOptions(
            name='budgetplan',
            options={'verbose_name': 'Rencana Anggaran Biaya', 'verbose_name_plural': 'Rencana Anggaran Biaya'},
        ),
        migrations.AlterModelOptions(
            name='joborder',
            options={'verbose_name': 'Job Order', 'verbose_name_plural': 'Job Orders'},
        ),
        migrations.AlterModelOptions(
            name='mandor',
            options={'verbose_name': 'Mandor', 'verbose_name_plural': 'Mandor-Mandor'},
        ),
        migrations.AlterModelOptions(
            name='servicebill',
            options={'verbose_name': 'Service Bill', 'verbose_name_plural': 'Service Bills'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'Service Order', 'verbose_name_plural': 'Service Orders'},
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='mandor_name',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='client_name',
        ),
        migrations.AddField(
            model_name='servicebill',
            name='client_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.Client', verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='receivingreport',
            name='items',
            field=models.ManyToManyField(through='arfi.Transaction', to='arfi.Item', verbose_name='Items list'),
        ),
        migrations.AddField(
            model_name='receivingreport',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.Supplier', verbose_name='Supplier ID'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='items',
            field=models.ManyToManyField(through='arfi.Transaction', to='arfi.Item', verbose_name='Items list'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.Supplier', verbose_name='Supplier ID'),
        ),
    ]
