# Generated by Django 2.1.4 on 2018-12-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arfi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='No.Order')),
                ('job_info', models.CharField(max_length=1000, verbose_name='Uraian Pekerjaan')),
                ('volume', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.BigIntegerField(verbose_name='Harga')),
                ('amount', models.BigIntegerField(verbose_name='Jumlah')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Client ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Client')),
                ('address', models.CharField(max_length=500, verbose_name='Alamat')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='No.Order')),
                ('date', models.DateTimeField(verbose_name='Tanggal')),
                ('mandor_name', models.CharField(max_length=200, verbose_name='Nama Mandor')),
                ('job_info', models.CharField(max_length=1000, verbose_name='Uraian Pekerjaan')),
            ],
        ),
        migrations.CreateModel(
            name='Mandor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mandor ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Mandor')),
                ('address', models.CharField(max_length=500, verbose_name='Alamat')),
                ('phone', models.CharField(max_length=20, verbose_name='No. HP')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='No.Order')),
                ('date', models.DateTimeField(verbose_name='Tanggal')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nama Client')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nama Proyek')),
                ('address', models.CharField(max_length=500, verbose_name='Alamat')),
                ('price', models.BigIntegerField(verbose_name='Harga')),
                ('total_price', models.BigIntegerField(verbose_name='Total Harga')),
                ('jobs', models.ManyToManyField(to='arfi.JobOrder', verbose_name='List Pekerjaan')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='No.Order')),
                ('date', models.DateTimeField(verbose_name='Tanggal')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nama Client')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nama Proyek')),
                ('address', models.CharField(max_length=500, verbose_name='Alamat')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.Client', verbose_name='Client ID')),
                ('jobs', models.ManyToManyField(to='arfi.JobOrder', verbose_name='List Pekerjaan')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='servicebill',
            name='service_order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.ServiceOrder', verbose_name='Service Order ID'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='mandor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.Mandor', verbose_name='Mandor ID'),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='service_order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='arfi.ServiceOrder', verbose_name='Service Order ID'),
        ),
    ]
