# Generated by Django 2.1.4 on 2018-12-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arfi', '0003_add_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebill',
            name='client_name',
        ),
    ]
