# Generated by Django 2.1.4 on 2018-12-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arfi', '0005_add_purchase_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplan',
            name='job_info',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Uraian Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='budgetplan',
            name='unit',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetplan',
            name='volume',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nama Client'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Nama Barang'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Tanggal Diperbaharui'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='mandor',
            name='address',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='mandor',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nama Mandor'),
        ),
        migrations.AlterField(
            model_name='mandor',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='confirmation',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='servicebill',
            name='address',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='servicebill',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='servicebill',
            name='project_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nama Proyek'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='address',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='project_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nama Proyek'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nama Supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
